import bcrypt from 'bcryptjs';

const defaultPass = bcrypt.hashSync('password123', 10);

export const memoryStore = {
  users: [
    {
      _id: 'user_alex_01',
      username: 'alex',
      email: 'alex@chatly.io',
      password: defaultPass,
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
      bio: 'Creating smooth real-time web applications! 🚀',
      status: 'online',
      lastSeen: new Date().toISOString(),
      pinnedChats: [],
      mutedChats: [],
      privacy: { readReceipts: true, lastSeenVisibility: true },
      notificationSettings: { sound: true, desktop: true },
    },
    {
      _id: 'user_sarah_02',
      username: 'sarah',
      email: 'sarah@chatly.io',
      password: defaultPass,
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
      bio: 'UI/UX Designer & Frontend Dev ✨',
      status: 'online',
      lastSeen: new Date().toISOString(),
      pinnedChats: [],
      mutedChats: [],
      privacy: { readReceipts: true, lastSeenVisibility: true },
      notificationSettings: { sound: true, desktop: true },
    },
    {
      _id: 'user_david_03',
      username: 'david_tech',
      email: 'david@chatly.io',
      password: defaultPass,
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
      bio: 'Fullstack developer & coffee enthusiast ☕',
      status: 'offline',
      lastSeen: new Date(Date.now() - 3600000).toISOString(),
      pinnedChats: [],
      mutedChats: [],
      privacy: { readReceipts: true, lastSeenVisibility: true },
      notificationSettings: { sound: true, desktop: true },
    },
    {
      _id: 'user_emily_04',
      username: 'emily_pm',
      email: 'emily@chatly.io',
      password: defaultPass,
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
      bio: 'Product Manager 📊 Building Chatly features!',
      status: 'online',
      lastSeen: new Date().toISOString(),
      pinnedChats: [],
      mutedChats: [],
      privacy: { readReceipts: true, lastSeenVisibility: true },
      notificationSettings: { sound: true, desktop: true },
    },
    {
      _id: 'user_michael_05',
      username: 'michael_dev',
      email: 'michael@chatly.io',
      password: defaultPass,
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
      bio: 'Mobile iOS & Android Engineer 📱',
      status: 'offline',
      lastSeen: new Date(Date.now() - 7200000).toISOString(),
      pinnedChats: [],
      mutedChats: [],
      privacy: { readReceipts: true, lastSeenVisibility: true },
      notificationSettings: { sound: true, desktop: true },
    },
    {
      _id: 'user_jessica_06',
      username: 'jessica_ops',
      email: 'jessica@chatly.io',
      password: defaultPass,
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
      bio: 'DevOps & Cybersecurity Specialist 🔒',
      status: 'online',
      lastSeen: new Date().toISOString(),
      pinnedChats: [],
      mutedChats: [],
      privacy: { readReceipts: true, lastSeenVisibility: true },
      notificationSettings: { sound: true, desktop: true },
    },
    {
      _id: 'user_liam_07',
      username: 'liam_ai',
      email: 'liam@chatly.io',
      password: defaultPass,
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=300&q=80',
      bio: 'AI & Machine Learning Researcher 🤖',
      status: 'offline',
      lastSeen: new Date(Date.now() - 14400000).toISOString(),
      pinnedChats: [],
      mutedChats: [],
      privacy: { readReceipts: true, lastSeenVisibility: true },
      notificationSettings: { sound: true, desktop: true },
    },
    {
      _id: 'user_sophia_08',
      username: 'sophia_gaming',
      email: 'sophia@chatly.io',
      password: defaultPass,
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
      bio: 'Community Lead & Gamer 🎮',
      status: 'online',
      lastSeen: new Date().toISOString(),
      pinnedChats: [],
      mutedChats: [],
      privacy: { readReceipts: true, lastSeenVisibility: true },
      notificationSettings: { sound: true, desktop: true },
    },
  ],
  conversations: [
    {
      _id: 'conv_1',
      isGroup: false,
      name: '',
      groupImage: '',
      description: '',
      admin: null,
      participants: ['user_alex_01', 'user_sarah_02'],
      lastMessage: 'msg_2',
      unreadCounts: { user_alex_01: 0, user_sarah_02: 0 },
      updatedAt: new Date(Date.now() - 60000).toISOString(),
      createdAt: new Date(Date.now() - 3600000).toISOString(),
    },
    {
      _id: 'conv_2',
      isGroup: true,
      name: 'Chatly Core Team',
      groupImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=300&q=80',
      description: 'Collaborating on Chatly real-time features',
      admin: 'user_alex_01',
      participants: ['user_alex_01', 'user_sarah_02', 'user_david_03', 'user_emily_04'],
      lastMessage: 'msg_3',
      unreadCounts: { user_alex_01: 0, user_sarah_02: 1 },
      updatedAt: new Date(Date.now() - 120000).toISOString(),
      createdAt: new Date(Date.now() - 86400000).toISOString(),
    },
  ],
  messages: [
    {
      _id: 'msg_1',
      conversation: 'conv_1',
      sender: 'user_sarah_02',
      text: 'Hey Alex! Have you tested the new Chatly interface?',
      attachments: [],
      replyTo: null,
      reactions: [{ user: 'user_alex_01', emoji: '❤️' }],
      status: 'read',
      readBy: ['user_alex_01', 'user_sarah_02'],
      isEdited: false,
      isDeleted: false,
      createdAt: new Date(Date.now() - 300000).toISOString(),
    },
    {
      _id: 'msg_2',
      conversation: 'conv_1',
      sender: 'user_alex_01',
      text: 'Yes! The smooth glassmorphic UI and real-time Socket.IO sync are super fast 🔥',
      attachments: [],
      replyTo: 'msg_1',
      reactions: [],
      status: 'read',
      readBy: ['user_alex_01', 'user_sarah_02'],
      isEdited: false,
      isDeleted: false,
      createdAt: new Date(Date.now() - 60000).toISOString(),
    },
    {
      _id: 'msg_3',
      conversation: 'conv_2',
      sender: 'user_emily_04',
      text: 'Welcome everyone to the Chatly Core Team group! 🚀',
      attachments: [],
      replyTo: null,
      reactions: [{ user: 'user_alex_01', emoji: '🎉' }],
      status: 'read',
      readBy: ['user_sarah_02', 'user_alex_01'],
      isEdited: false,
      isDeleted: false,
      createdAt: new Date(Date.now() - 120000).toISOString(),
    },
  ],
  notifications: [],
};
